package com.arlight.buildbattle;
import com.arlight.core.api.*;import com.arlight.core.network.VisualScoreboardNetwork;import org.bukkit.*;import org.bukkit.block.Block;import org.bukkit.block.data.BlockData;import org.bukkit.command.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.entity.*;import org.bukkit.event.inventory.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.*;import org.bukkit.plugin.java.JavaPlugin;import org.bukkit.scheduler.BukkitTask;import java.util.*;
public final class ArlightBuildBattlePlugin extends JavaPlugin implements Listener,CommandExecutor,TabCompleter{
 enum State{WAITING,COUNTDOWN,PROPOSALS,THEME_VOTE,BUILDING,BUILD_VOTE,ENDING}private State state=State.WAITING;private final Set<UUID> players=new LinkedHashSet<>();private final List<UUID> plotOwners=new ArrayList<>();private final Map<UUID,String> proposals=new LinkedHashMap<>();private final Map<UUID,String> themeVotes=new HashMap<>();private final Map<UUID,Integer> plotOf=new HashMap<>();private final Map<Integer,Map<UUID,Integer>> buildVotes=new HashMap<>();private final Map<BlockPos,BlockData> plotSnapshot=new HashMap<>();private WaitingScreenNetwork waitingScreen; private BukkitTask task;private int seconds,currentPlot;private String theme="";private Location origin;
 public void onEnable(){saveDefaultConfig();getCommand("buildbattle").setExecutor(this);getCommand("buildbattle").setTabCompleter(this);getServer().getPluginManager().registerEvents(this,this); waitingScreen=new WaitingScreenNetwork(this); getServer().getMessenger().registerOutgoingPluginChannel(this,WaitingScreenNetwork.CHANNEL); ArlightCoreAPI.registerMinigame(new Provider());prepare();task=getServer().getScheduler().runTaskTimer(this,this::tick,20,20);}public void onDisable(){if(task!=null)task.cancel();cleanup();for(UUID id:new ArrayList<>(players)){Player p=Bukkit.getPlayer(id);if(p!=null)ArlightCoreAPI.endMinigameSession(p);}for(UUID waitingId:new ArrayList<>(players)){Player waitingPlayer=Bukkit.getPlayer(waitingId);if(waitingPlayer!=null&&waitingScreen!=null)waitingScreen.hide(waitingPlayer);} getServer().getMessenger().unregisterOutgoingPluginChannel(this,WaitingScreenNetwork.CHANNEL); ArlightCoreAPI.unregisterMinigame("buildbattle");}
 private World world(){World w=Bukkit.getWorld(getConfig().getString("world.name","vacio"));if(w==null)w=Bukkit.createWorld(new WorldCreator("vacio").generator(new Empty()));return w;}private int min(){return getConfig().getInt("game.minimum-players",2);}private int max(){return getConfig().getInt("game.maximum-players",12);}private int size(){return getConfig().getInt("plots.size",32);}private int gap(){return getConfig().getInt("plots.gap",12);}
 private void prepare(){origin=new Location(world(),getConfig().getInt("plots.origin.x",0),getConfig().getInt("plots.origin.y",80),getConfig().getInt("plots.origin.z",0));ArlightCoreAPI.configureInventoryGroup("buildbattle","vacio",null,null);cleanup();}
 private boolean join(Player p){if(state.ordinal()>=State.BUILDING.ordinal()||players.size()>=max()||!ArlightCoreAPI.beginMinigameSession(p,"buildbattle"))return false;players.add(p.getUniqueId());p.sendMessage("§e§lBuild Battle §8» §aEntraste a la cola.");show(p);updateWaitingScreens(true); return true;}private void leave(Player p,boolean d){if(waitingScreen!=null)waitingScreen.hide(p);players.remove(p.getUniqueId());proposals.remove(p.getUniqueId());themeVotes.remove(p.getUniqueId());if(state.ordinal()<State.BUILDING.ordinal())plotOf.remove(p.getUniqueId());ArlightCoreAPI.clearVisualScoreboard(p);if(!d)ArlightCoreAPI.endMinigameSession(p);updateWaitingScreens(false);}
 private void tick(){switch(state){case WAITING->{if(players.size()>=min()){state=State.COUNTDOWN;seconds=getConfig().getInt("game.auto-start-seconds",20);}}case COUNTDOWN->{if(players.size()<min())state=State.WAITING;else if(--seconds<=0)startProposals();}case PROPOSALS->{if(--seconds<=0)startThemeVote();}case THEME_VOTE->{if(--seconds<=0)startBuild();}case BUILDING->{if(--seconds<=0)startBuildVote();}case BUILD_VOTE->{if(--seconds<=0)nextPlot();}default->{}}for(UUID id:players){Player p=Bukkit.getPlayer(id);if(p!=null)show(p);}updateWaitingScreens(false);}
 private void startProposals(){state=State.PROPOSALS;seconds=getConfig().getInt("phases.proposal-seconds",20);proposals.clear();broadcast("§fEscribe §e/bb theme <tema> §fpara proponer un tema.");}
 private boolean validTheme(String t){if(t.length()<3||t.length()>getConfig().getInt("themes.maximum-length",32)||t.matches(".*https?://.*"))return false;String low=t.toLowerCase(Locale.ROOT);for(String b:getConfig().getStringList("themes.blocked-words"))if(low.contains(b.toLowerCase(Locale.ROOT)))return false;return proposals.values().stream().noneMatch(v->v.equalsIgnoreCase(t));}
 private void startThemeVote(){if(proposals.isEmpty()){proposals.put(UUID.randomUUID(),"Cachalote");proposals.put(UUID.randomUUID(),"Castillo mágico");}state=State.THEME_VOTE;seconds=getConfig().getInt("phases.theme-voting-seconds",20);for(UUID id:players){Player p=Bukkit.getPlayer(id);if(p!=null)openThemeMenu(p);}}
 private void openThemeMenu(Player p){int rows=Math.max(1,Math.min(6,(proposals.size()+8)/9));Inventory inv=Bukkit.createInventory(null,rows*9,"§eVota por un tema");int slot=0;for(String t:proposals.values()){ItemStack i=new ItemStack(Material.PAPER);ItemMeta m=i.getItemMeta();m.setDisplayName("§e"+t);m.setLore(List.of("§7Click para votar"));i.setItemMeta(m);inv.setItem(slot++,i);}p.openInventory(inv);}
 private void startBuild(){Map<String,Long> counts=new HashMap<>();for(String v:themeVotes.values())counts.merge(v,1L,Long::sum);theme=counts.entrySet().stream().max(Map.Entry.comparingByValue()).map(Map.Entry::getKey).orElseGet(()->proposals.values().iterator().next());state=State.BUILDING;seconds=getConfig().getInt("phases.building-seconds",480);plotOwners.clear();plotOf.clear();buildVotes.clear();plotSnapshot.clear();for(UUID id:List.copyOf(players)){Player p=Bukkit.getPlayer(id);if(p==null)continue;int plotIndex=plotOwners.size();plotOwners.add(id);plotOf.put(id,plotIndex);snapshotPlot(plotIndex);createPlot(plotIndex);ArlightCoreAPI.markMinigameStarted(p);p.setGameMode(GameMode.CREATIVE);p.setAllowFlight(true);p.teleport(plotCenter(plotIndex).add(0,2,0));giveTools(p);}broadcast("§fTema ganador: §e§l"+theme);}
 private void snapshotPlot(int idx){Location c=plotCenter(idx);int half=size()/2+2,minY=origin.getBlockY()-2,maxY=origin.getBlockY()+getConfig().getInt("plots.max-height",48)+4;World w=world();for(int x=-half;x<=half;x++)for(int z=-half;z<=half;z++)for(int y=minY;y<=maxY;y++){Block b=w.getBlockAt(c.getBlockX()+x,y,c.getBlockZ()+z);plotSnapshot.putIfAbsent(new BlockPos(b.getX(),b.getY(),b.getZ()),b.getBlockData().clone());}}
 private void createPlot(int idx){Location c=plotCenter(idx);int half=size()/2;for(int x=-half;x<=half;x++)for(int z=-half;z<=half;z++){Block b=world().getBlockAt(c.getBlockX()+x,origin.getBlockY(),c.getBlockZ()+z);b.setType(Material.WHITE_CONCRETE,false);}}
 private Location plotCenter(int idx){int cols=4,row=idx/cols,col=idx%cols;return origin.clone().add(col*(size()+gap()),0,row*(size()+gap()));}
 private void giveTools(Player p){p.getInventory().clear();p.getInventory().setItem(8,item(Material.NETHER_STAR,"§eMenú de parcela",13001));}
 private boolean inOwnPlot(Player p,Block b){Integer idx=plotOf.get(p.getUniqueId());if(idx==null)return false;Location c=plotCenter(idx);int h=size()/2;return b.getWorld().equals(world())&&Math.abs(b.getX()-c.getBlockX())<=h&&Math.abs(b.getZ()-c.getBlockZ())<=h&&b.getY()>=origin.getBlockY()&&b.getY()<=origin.getBlockY()+getConfig().getInt("plots.max-height",48);}
 private void startBuildVote(){state=State.BUILD_VOTE;currentPlot=0;if(plotOwners.isEmpty()){finish();return;}seconds=getConfig().getInt("phases.voting-seconds-per-plot",10);teleportVote();}
 private void nextPlot(){currentPlot++;if(currentPlot>=plotOwners.size()){finish();return;}seconds=getConfig().getInt("phases.voting-seconds-per-plot",10);teleportVote();}
 private void teleportVote(){UUID owner=plotOwners.get(currentPlot);Integer plotIndex=plotOf.get(owner);if(plotIndex==null){nextPlot();return;}Location c=plotCenter(plotIndex).add(0,8,0);for(UUID id:players){Player p=Bukkit.getPlayer(id);if(p!=null){p.setGameMode(GameMode.ADVENTURE);p.setAllowFlight(true);p.setFlying(true);p.teleport(c);giveVoteItems(p);}}}
 private void giveVoteItems(Player p){p.getInventory().clear();Material[] ms={Material.GRAY_DYE,Material.RED_DYE,Material.YELLOW_DYE,Material.LIME_DYE,Material.LIGHT_BLUE_DYE,Material.PINK_DYE};String[] ns={"Muy mala","Mala","Normal","Buena","Épica","Legendaria"};for(int i=0;i<6;i++){ItemStack it=item(ms[i],"§f"+(i+1)+" §7- §e"+ns[i],13100+i);p.getInventory().setItem(i+1,it);}}
 private void finish(){if(state==State.ENDING)return;state=State.ENDING;List<UUID> order=new ArrayList<>(plotOwners);order.sort(Comparator.comparingDouble(this::score).reversed());if(!order.isEmpty()){Player w=Bukkit.getPlayer(order.get(0));if(w!=null){broadcast("§6§l"+w.getName()+" ganó con "+String.format(Locale.US,"%.2f",score(w.getUniqueId()))+" puntos.");ArlightCoreAPI.addWinXp(w);}}Map<UUID,UniversalPodiumResult>podiums=new HashMap<>();for(UUID id:players)podiums.put(id,createPodium(order,id));getServer().getScheduler().runTaskLater(this,()->{List<UUID>ending=new ArrayList<>(players);for(UUID id:ending){Player p=Bukkit.getPlayer(id);if(p!=null){ArlightCoreAPI.clearVisualScoreboard(p);ArlightCoreAPI.endMinigameSession(p);ArlightCoreAPI.teleportToLobby(p);}}players.clear();plotOwners.clear();proposals.clear();themeVotes.clear();plotOf.clear();buildVotes.clear();cleanup();state=State.WAITING;getServer().getScheduler().runTaskLater(this,()->{for(UUID id:ending){Player p=Bukkit.getPlayer(id);UniversalPodiumResult result=podiums.get(id);if(p!=null&&p.isOnline()&&result!=null)ArlightCoreAPI.showUniversalPodium(p,result);}},10L);},140);}
 private UniversalPodiumResult createPodium(List<UUID>order,UUID viewer){List<PodiumEntry>top=new ArrayList<>();for(int i=0;i<Math.min(3,order.size());i++){UUID id=order.get(i);top.add(new PodiumEntry(i+1,id,playerName(id),null,List.of(new PodiumStat("star","Promedio",String.format(Locale.US,"%.2f",score(id))),new PodiumStat("players","Votos",String.valueOf(voteCount(id))),new PodiumStat("info","Tema",theme))));}int place=order.indexOf(viewer)+1;List<PodiumStat>stats=List.of(new PodiumStat("trophy","Puesto",place<=0?"—":"#"+place),new PodiumStat("star","Puntuación",String.format(Locale.US,"%.2f",score(viewer))),new PodiumStat("players","Votos recibidos",String.valueOf(voteCount(viewer))),new PodiumStat("info","Tema",theme));return new UniversalPodiumResult("buildbattle","Build Battle","creative",theme.isBlank()?"Construcción terminada":"Tema: "+theme,280,"bb join",place,top,stats);}private int voteCount(UUID owner){Integer idx=plotOf.get(owner);return idx==null?0:buildVotes.getOrDefault(idx,Map.of()).size();}private String playerName(UUID id){Player p=Bukkit.getPlayer(id);if(p!=null)return p.getName();String n=Bukkit.getOfflinePlayer(id).getName();return n==null?id.toString().substring(0,8):n;}
 private double score(UUID owner){Integer idx=plotOf.get(owner);if(idx==null)return 0;Map<UUID,Integer> v=buildVotes.getOrDefault(idx,Map.of());return v.values().stream().mapToInt(Integer::intValue).average().orElse(0);}
 private void cleanup(){World w=world();for(Map.Entry<BlockPos,BlockData> entry:new HashMap<>(plotSnapshot).entrySet()){BlockPos p=entry.getKey();w.getBlockAt(p.x,p.y,p.z).setBlockData(entry.getValue(),false);}plotSnapshot.clear();for(Entity e:w.getEntities())if(!(e instanceof Player))e.remove();}
 private void show(Player p){List<VisualScoreboardNetwork.Line> ls=List.of(ArlightCoreAPI.visualLine("theme","Tema",theme.isBlank()?"Pendiente":theme),ArlightCoreAPI.visualLine("timer","Tiempo",fmt(seconds)),ArlightCoreAPI.visualLine("players","Jugadores",players.size()+"/"+max()),ArlightCoreAPI.visualLine("plot","Parcela",String.valueOf(plotOf.getOrDefault(p.getUniqueId(),-1)+1)));ArlightCoreAPI.showVisualScoreboard(p,"buildbattle","§eBuild Battle","Gracias holy.gg",state==State.BUILDING?seconds/(double)Math.max(1,getConfig().getInt("phases.building-seconds",480)):0,state.name(),ls);}private void updateWaitingScreens(boolean show){if(waitingScreen==null)return;if(!(state==State.WAITING||state==State.COUNTDOWN)){for(UUID id:players){Player p=Bukkit.getPlayer(id);if(p!=null)waitingScreen.hide(p);}return;}List<String>names=players.stream().map(Bukkit::getPlayer).filter(Objects::nonNull).map(Player::getName).toList();int countdown=state==State.COUNTDOWN?seconds:-1;String status=state==State.COUNTDOWN?"CUENTA_REGRESIVA":"ESPERANDO_JUGADORES";for(UUID id:players){Player p=Bukkit.getPlayer(id);if(p==null)continue;if(show)waitingScreen.show(p,players.size(),max(),countdown,status,names);else waitingScreen.update(p,players.size(),max(),countdown,status,names);}}
 private String fmt(int s){return String.format("%02d:%02d",Math.max(0,s)/60,Math.max(0,s)%60);}private void broadcast(String m){for(UUID id:players){Player p=Bukkit.getPlayer(id);if(p!=null)p.sendMessage("§e§lBuild Battle §8» "+m);}}
 @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked()instanceof Player p))return;if(state==State.THEME_VOTE&&e.getView().getTitle().equals("§eVota por un tema")){e.setCancelled(true);if(e.getCurrentItem()!=null&&e.getCurrentItem().hasItemMeta()){String t=ChatColor.stripColor(e.getCurrentItem().getItemMeta().getDisplayName());themeVotes.put(p.getUniqueId(),t);p.closeInventory();p.sendMessage("§aVotaste por §e"+t);}}}
 @EventHandler public void interact(PlayerInteractEvent e){Player p=e.getPlayer();if(state!=State.BUILD_VOTE||!players.contains(p.getUniqueId())||e.getItem()==null||currentPlot<0||currentPlot>=plotOwners.size())return;int slot=p.getInventory().getHeldItemSlot();if(slot<1||slot>6)return;e.setCancelled(true);UUID owner=plotOwners.get(currentPlot);Integer plotIndex=plotOf.get(owner);if(plotIndex==null)return;if(owner.equals(p.getUniqueId())){p.sendMessage("§cNo puedes votar por tu propia construcción.");return;}buildVotes.computeIfAbsent(plotIndex,k->new HashMap<>()).put(p.getUniqueId(),slot);p.sendActionBar("§eVoto: §f"+slot+"/6");}
 @EventHandler public void place(BlockPlaceEvent e){if(!players.contains(e.getPlayer().getUniqueId()))return;if(state!=State.BUILDING||!inOwnPlot(e.getPlayer(),e.getBlock()))e.setCancelled(true);}@EventHandler public void br(BlockBreakEvent e){if(!players.contains(e.getPlayer().getUniqueId()))return;if(state!=State.BUILDING||!inOwnPlot(e.getPlayer(),e.getBlock()))e.setCancelled(true);}@EventHandler public void move(PlayerMoveEvent e){if(state==State.BUILDING&&players.contains(e.getPlayer().getUniqueId())){Integer idx=plotOf.get(e.getPlayer().getUniqueId());if(idx!=null&&!inPlotLoc(idx,e.getTo()))e.getPlayer().teleport(plotCenter(idx).add(0,2,0));}}private boolean inPlotLoc(int idx,Location l){Location c=plotCenter(idx);int h=size()/2+1;return l.getWorld().equals(world())&&Math.abs(l.getX()-c.getX())<=h&&Math.abs(l.getZ()-c.getZ())<=h&&l.getY()>origin.getY()-5&&l.getY()<origin.getY()+getConfig().getInt("plots.max-height",48)+8;}
 @EventHandler public void quit(PlayerQuitEvent e){if(players.contains(e.getPlayer().getUniqueId()))leave(e.getPlayer(),true);}@EventHandler public void damage(EntityDamageEvent e){if(e.getEntity()instanceof Player p&&players.contains(p.getUniqueId()))e.setCancelled(true);}
 public boolean onCommand(CommandSender s,Command c,String l,String[]a){if(a.length==0){s.sendMessage("§e/bb join|leave|theme|stats|admin");return true;}switch(a[0].toLowerCase()){case"join"->{if(s instanceof Player p&&!ArlightCoreAPI.joinQueue(p,"buildbattle"))p.sendMessage("§cNo puedes entrar.");}case"leave"->{if(s instanceof Player p)leave(p,false);}case"theme"->{if(!(s instanceof Player p)||state!=State.PROPOSALS||a.length<2)return true;String t=String.join(" ",Arrays.copyOfRange(a,1,a.length)).trim();if(!validTheme(t)){p.sendMessage("§cTema inválido o repetido.");return true;}proposals.put(p.getUniqueId(),t);p.sendMessage("§aPropusiste: §e"+t);}case"stats"->s.sendMessage("§eEstadísticas almacenadas por ArlightCore.");case"admin"->{if(!s.hasPermission("arlightbuildbattle.admin"))return true;if(a.length>1&&a[1].equalsIgnoreCase("forcestart"))startProposals();else if(a.length>1&&a[1].equalsIgnoreCase("skip")){seconds=1;}else if(a.length>1&&a[1].equalsIgnoreCase("clear"))cleanup();else if(a.length>1&&a[1].equalsIgnoreCase("reload")){reloadConfig();s.sendMessage("§aRecargado.");}}}return true;}public List<String>onTabComplete(CommandSender s,Command c,String l,String[]a){return a.length==1?List.of("join","leave","theme","stats","admin"):a.length==2&&a[0].equalsIgnoreCase("admin")?List.of("forcestart","skip","clear","reload"):List.of();}
 private ItemStack item(Material mat,String name,int cmd){ItemStack i=new ItemStack(mat);ItemMeta m=i.getItemMeta();m.setDisplayName(name);m.setCustomModelData(cmd);i.setItemMeta(m);return i;}private final class Provider implements MinigameProvider{public String getId(){return"buildbattle";}public String getDisplayName(){return"§eBuild Battle";}public ItemStack getIcon(){return item(Material.BRICKS,"§eBuild Battle",13000);}public MinigameStatus getStatus(){return state==State.WAITING||state==State.COUNTDOWN?MinigameStatus.WAITING:state==State.ENDING?MinigameStatus.RESTARTING:MinigameStatus.IN_PROGRESS;}public void join(Player p){if(!ArlightBuildBattlePlugin.this.join(p))throw new IllegalStateException();}public void leave(Player p){ArlightBuildBattlePlugin.this.leave(p,false);}public void handleDisconnect(Player p){ArlightBuildBattlePlugin.this.leave(p,true);}public boolean isPlaying(Player p){return players.contains(p.getUniqueId());}public int getCurrentPlayers(){return players.size();}public int getMaxPlayers(){return max();}}
 private record BlockPos(int x,int y,int z){}private static final class Empty extends org.bukkit.generator.ChunkGenerator{public ChunkData generateChunkData(World w,Random r,int x,int z,BiomeGrid b){return createChunkData(w);}}
}
